{
    "issue": {
        "title": "[R] calling invalidate() method on ArrowObjects causes subsequent segfault",
        "body": "***Note**: This issue was originally created as [ARROW-15677](https://issues.apache.org/jira/browse/ARROW-15677). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nTrying to access invalidated dataset results in segfaults on OSX.\r\n\r\n\u00a0\r\n\r\nlibrary(arrow, warn.conflicts = FALSE)\r\nmy_array <- Array$create(array((1:100000) + 1L, rep(100, 3)))\r\nmy_array$invalidate()\r\nmy_array$length()\r\n\r\n\u00a0\r\n\r\nResults:\r\n\r\n\u00a0\\*\\*\\* caught segfault \\*\\*\\*\r\naddress 0xffff01000008, cause 'invalid permissions'\r\n\r\nTraceback:\r\n\u00a01: Array__length(self)\r\n\u00a02: my_array$length()\r\n\r\nPossible actions:\r\n1: abort (with core dump, if enabled)\r\n2: normal R exit\r\n3: exit R without saving workspace\r\n4: exit R saving workspace",
        "created_at": "2022-02-14T14:50:13.000Z",
        "updated_at": "2022-02-17T02:01:26.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: R",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2022-02-16T17:10:11.000Z"
    },
    "comments": [
        {
            "created_at": "2022-02-14T15:25:07.973Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17492057) by Nicola Crane (thisisnic):*\nHere's the output of running the above code with the debugger attached\r\n\r\n\r\n```cpp\n\r\n(gdb) run\r\nStarting program: /usr/lib/R/bin/exec/R \r\n[Thread debugging using libthread_db enabled]\r\nUsing host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\".\r\n\r\nR version 4.1.2 (2021-11-01) -- \"Bird Hippie\"\r\nCopyright (C) 2021 The R Foundation for Statistical Computing\r\nPlatform: x86_64-pc-linux-gnu (64-bit)\r\n\r\nR is free software and comes with ABSOLUTELY NO WARRANTY.\r\nYou are welcome to redistribute it under certain conditions.\r\nType 'license()' or 'licence()' for distribution details.\r\n\r\n  Natural language support but running in an English locale\r\n\r\nR is a collaborative project with many contributors.\r\nType 'contributors()' for more information and\r\n'citation()' on how to cite R or R packages in publications.\r\n\r\nType 'demo()' for some demos, 'help()' for on-line help, or\r\n'help.start()' for an HTML browser interface to help.\r\nType 'q()' to quit R.\r\n\r\n[Detaching after vfork from child process 447650]\r\n[Detaching after vfork from child process 447652]\r\n> library(arrow, warn.conflicts = FALSE)\r\n[New Thread 0x7ffff326c700 (LWP 447696)]\r\n\r\n[New Thread 0x7fffeb7ff700 (LWP 447702)]\r\n> my_array <- Array$create(array((1:100000) + 1L, rep(100, 3)))\r\n> my_array$invalidate()\r\n> my_array$length()\r\n\r\nThread 1 \"R\" received signal SIGSEGV, Segmentation fault.\r\n0x00007ffff2628d4a in std::__shared_ptr<arrow::ArrayData, (__gnu_cxx::_Lock_policy)2>::get (this=0xffff01000008)\r\n    at /usr/include/c++/9/bits/shared_ptr_base.h:1310\r\n1310\t      { return _M_ptr; }\r\n\r\n```\r\n"
        },
        {
            "created_at": "2022-02-15T13:45:48.334Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17492617) by Nicola Crane (thisisnic):*\nThanks for reporting this `[~qtmaicw66]` .\u00a0 Just to check, can you tell me a bit more about what you're trying to do here, by calling `{}invalidate(){`}?\u00a0 It looks like a method which has been left there as a relic of some earlier internal code which has now been removed, so we may look to remove it altogether."
        },
        {
            "created_at": "2022-02-15T13:53:07.212Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17492621) by qtmaicw66 (qtmaicw66):*\n`[~thisisnic]` I was playing with the R package trying to figure out the use-cases. Then I encountered this error. Strictly speaking I shouldn't call any method after invalidating the data, but wasn't expecting the segfault. So I reported this issue here :)"
        },
        {
            "created_at": "2022-02-15T14:06:10.339Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17492629) by Nicola Crane (thisisnic):*\nOK, great, and thanks for letting us know!\u00a0"
        },
        {
            "created_at": "2022-02-16T12:55:52.150Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17493218) by Nicola Crane (thisisnic):*\nAlso `[~qtmaicw66]` \u00a0 if you're curious about use-cases, you might find the cookbook helpful; it's written from a task-oriented point-of-view and can be found here: https://arrow.apache.org/cookbook/r/"
        },
        {
            "created_at": "2022-02-16T17:10:11.772Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-15677?focusedCommentId=17493357) by Nicola Crane (thisisnic):*\nIssue resolved by pull request 12430\n<https://github.com/apache/arrow/pull/12430>"
        }
    ]
}