{
    "issue": {
        "title": "[Python][C++] Crash when deserializing from components in a fresh new process",
        "body": "***Note**: This issue was originally created as [ARROW-5260](https://issues.apache.org/jira/browse/ARROW-5260). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nTrying to deserialize a table from component in a fresh new process crashes with sigsegv:\r\n```\n\r\n#1 0x00007fffd5eb93f0 in arrow::py::unwrap_buffer(_object*, std::shared_ptr<arrow::Buffer>*) ()\r\nfrom /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/./libarrow_python.so.13\r\n#2 0x00007fffd5e69260 in arrow::py::GetSerializedFromComponents(int, int, int, _object*, arrow::py::SerializedPyObject*) () from /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/./libarrow_python.so.13\r\n#3 0x00007fffd6b1cafe in __pyx_pw_7pyarrow_3lib_18SerializedPyObject_7from_components(_object*, _object*, _object*) () from /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so\r\n#4 0x00000000004ad919 in PyCFunction_Call ()\r\n#5 0x00007fffd6a88d10 in __Pyx_PyObject_Call(_object*, _object*, _object*) [clone .constprop.1186] ()\r\nfrom /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so\r\n#6 0x00007fffd6a41872 in __Pyx__PyObject_CallOneArg(_object*, _object*) ()\r\nfrom /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so\r\n#7 0x00007fffd6a89e59 in __Pyx_PyObject_CallOneArg(_object*, _object*) ()\r\nfrom /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so\r\n#8 0x00007fffd6ab087f in __pyx_pw_7pyarrow_3lib_165deserialize_components(_object*, _object*, _object*) ()\r\nfrom /home/yevgeni/uatc/.petastorm3.6/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so\r\n#9 0x00000000004adca7 in _PyCFunction_FastCallKeywords ()\r\n#10 0x0000000000545e34 in ?? ()\r\n#11 0x000000000054ac8c in _PyEval_EvalFrameDefault ()\r\n#12 0x0000000000545a51 in ?? ()\r\n#13 0x0000000000546890 in PyEval_EvalCode ()\r\n#14 0x000000000042a9a8 in PyRun_FileExFlags ()\r\n#15 0x000000000042ab8d in PyRun_SimpleFileExFlags ()\r\n#16 0x000000000043e0ba in Py_Main ()\r\n#17 0x0000000000421b04 in main ()\r\n```\r\n\u00a0The following snippet can be used to reproduce the issue:\r\n```java\n\r\nimport pickle\r\nimport sys\r\n\r\nimport pandas as pd\r\nimport pyarrow as pa\r\n\r\nif __name__ == '__main__':\r\n    if sys.argv[1] == 'w':\r\n        df = pd.DataFrame({'int': [1, 2], 'str': ['a', 'b']})\r\n        table = pa.Table.from_pandas(df)\r\n        table_serialized = pa.serialize(table)\r\n        table_serialized_components = table_serialized.to_components()\r\n        with open('/tmp/p.pickle', 'wb') as f:\r\n            pickle.dump(table_serialized_components, f)\r\n        print('/tmp/p.pickle written ok')\r\n\r\n    if sys.argv[1] == 'r':\r\n# UNCOMMENT THE FOLLOWING LINE TO AVOID THE CRASH\r\n        #pa.serialize(0)\r\n        with open('/tmp/p.pickle', 'rb') as f:\r\n            table_serialized_components = pickle.load(f)\r\n        table = pa.deserialize_components(table_serialized_components)\r\n        print(table)\r\n\r\n```\r\nThen run:\r\n```java\n\r\n$ python pa_serialization_crashes.py w\r\n/tmp/p.pickle written ok\r\n\r\n$ python pa_serialization_crashes.py r\r\nSegmentation fault (core dumped)\n```\r\nThe crash would not occur if you try to serialize\u00a0unrelated data before\u00a0the deserialization (see a commented out line in the reproduction instructions)\r\n\r\n\u00a0",
        "created_at": "2019-05-05T05:00:38.000Z",
        "updated_at": "2019-05-20T18:36:54.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: C++",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2019-05-20T16:58:40.000Z"
    },
    "comments": [
        {
            "created_at": "2019-05-20T16:58:40.966Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-5260?focusedCommentId=16844112) by Antoine Pitrou (apitrou):*\nIssue resolved by pull request 4267\n<https://github.com/apache/arrow/pull/4267>"
        }
    ]
}