{
    "issue": {
        "title": "[Python] Improve error message when object of wrong type is given",
        "body": "***Note**: This issue was originally created as [ARROW-6936](https://issues.apache.org/jira/browse/ARROW-6936). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nIn the PyArrow `unwrap_xxx` functions, the error messages when an object of the wrong type is given are not very informative (e.g. \"Could not unwrap Buffer from the passed Python object.\").",
        "created_at": "2019-10-18T13:41:36.000Z",
        "updated_at": "2019-10-21T11:02:33.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Python",
            "Type: enhancement"
        ],
        "closed": true,
        "closed_at": "2019-10-21T11:02:32.000Z"
    },
    "comments": [
        {
            "created_at": "2019-10-21T11:02:32.718Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6936?focusedCommentId=16955952) by Krisztian Szucs (kszucs):*\nIssue resolved by pull request 5696\n<https://github.com/apache/arrow/pull/5696>"
        }
    ]
}