{
    "issue": {
        "title": "[CI][Python] Failing conda-python-3.8-jpype Nightly Build",
        "body": "***Note**: This issue was originally created as [ARROW-11146](https://issues.apache.org/jira/browse/ARROW-11146). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nThe build segfaults after running the Python tests.",
        "created_at": "2021-01-06T15:55:25.000Z",
        "updated_at": "2021-05-05T21:56:55.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Continuous Integration",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2021-05-05T20:52:15.000Z"
    },
    "comments": [
        {
            "created_at": "2021-04-27T19:02:11.140Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11146?focusedCommentId=17333489) by Antoine Pitrou (apitrou):*\n`[~uwe]` Are you interested in fixing this? Otherwise we should probably simply disable the build.\r\n\r\nNote: example failing build: https://github.com/ursacomputing/crossbow/runs/2445195385"
        },
        {
            "created_at": "2021-04-27T19:03:13.336Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11146?focusedCommentId=17333490) by Mauricio 'Pach\u00e1' Vargas Sep\u00falveda (pachamaltese):*\nrelated: https://issues.apache.org/jira/browse/ARROW-12572"
        },
        {
            "created_at": "2021-05-05T20:52:15.474Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11146?focusedCommentId=17339891) by Jonathan Keane (jonkeane):*\nIssue resolved by pull request 10238\n<https://github.com/apache/arrow/pull/10238>"
        }
    ]
}