{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "id": "13445367",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367",
    "key": "ARROW-16592",
    "fields": {
        "fixVersions": [
            {
                "self": "https://issues.apache.org/jira/rest/api/2/version/12351550",
                "id": "12351550",
                "name": "9.0.0",
                "archived": false,
                "released": true,
                "releaseDate": "2022-08-03"
            }
        ],
        "resolution": {
            "self": "https://issues.apache.org/jira/rest/api/2/resolution/1",
            "id": "1",
            "description": "A fix for this issue is checked into the tree and tested.",
            "name": "Fixed"
        },
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312320": null,
        "customfield_12310420": "9223372036854775807",
        "customfield_12312321": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312326": null,
        "customfield_12310300": null,
        "customfield_12312327": null,
        "customfield_12312324": null,
        "customfield_12312720": null,
        "customfield_12312325": null,
        "lastViewed": null,
        "priority": {
            "self": "https://issues.apache.org/jira/rest/api/2/priority/3",
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
            "name": "Major",
            "id": "3"
        },
        "labels": [
            "pull-request-available"
        ],
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12313422": "false",
        "customfield_12310310": "0.0",
        "customfield_12312331": null,
        "customfield_12312332": null,
        "aggregatetimeoriginalestimate": null,
        "timeestimate": 0,
        "customfield_12312330": null,
        "versions": [],
        "customfield_12311120": null,
        "customfield_12313826": null,
        "customfield_12312339": null,
        "issuelinks": [],
        "customfield_12313825": null,
        "assignee": {
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
            "name": "lidavidm",
            "key": "lidavidm",
            "avatarUrls": {
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "David Li",
            "active": true,
            "timeZone": "America/New_York"
        },
        "customfield_12312337": null,
        "customfield_12313823": null,
        "customfield_12312338": null,
        "customfield_12311920": null,
        "customfield_12313822": null,
        "customfield_12312335": null,
        "customfield_12313821": null,
        "customfield_12312336": null,
        "customfield_12313820": null,
        "status": {
            "self": "https://issues.apache.org/jira/rest/api/2/status/5",
            "description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/resolved.png",
            "name": "Resolved",
            "id": "5",
            "statusCategory": {
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3",
                "id": 3,
                "key": "done",
                "colorName": "green",
                "name": "Done"
            }
        },
        "components": [
            {
                "self": "https://issues.apache.org/jira/rest/api/2/component/12334621",
                "id": "12334621",
                "name": "FlightRPC"
            },
            {
                "self": "https://issues.apache.org/jira/rest/api/2/component/12328936",
                "id": "12328936",
                "name": "Python"
            }
        ],
        "customfield_12312026": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "aggregatetimeestimate": 0,
        "customfield_12312022": null,
        "customfield_12310921": null,
        "customfield_12310920": "9223372036854775807",
        "customfield_12312823": null,
        "creator": {
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
            "name": "lupko",
            "key": "JIRAUSER286791",
            "avatarUrls": {
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Lubo Slivka",
            "active": true,
            "timeZone": "Europe/Prague"
        },
        "subtasks": [],
        "reporter": {
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
            "name": "lupko",
            "key": "JIRAUSER286791",
            "avatarUrls": {
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Lubo Slivka",
            "active": true,
            "timeZone": "Europe/Prague"
        },
        "aggregateprogress": {
            "progress": 3000,
            "total": 3000,
            "percent": 100
        },
        "customfield_12313520": null,
        "customfield_12310250": null,
        "progress": {
            "progress": 3000,
            "total": 3000,
            "percent": 100
        },
        "customfield_12313924": null,
        "votes": {
            "self": "https://issues.apache.org/jira/rest/api/2/issue/ARROW-16592/votes",
            "votes": 0,
            "hasVoted": false
        },
        "worklog": {
            "startAt": 0,
            "maxResults": 20,
            "total": 5,
            "worklogs": [
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/worklog/772104",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "comment": "lidavidm opened a new pull request, #13191:\nURL: https://github.com/apache/arrow/pull/13191\n\n   Currently a failed write (due to the server sending an error,\r\n   disconnecting, etc.) will raise an uninformative error on the\r\n   client. Prior to the refactoring done in Arrow 8.0.0, this was\r\n   silently swallowed (so clients would not get any indication until\r\n   they finished writing). In 8.0.0 instead the error got propagated\r\n   but this led to confusing, uninformative errors. Instead, tag this\r\n   specific error so that the client implementation knows to finish\r\n   the call and get the actual server error.\r\n   \r\n   (gRPC doesn't give us the actual error until we explicitly finish\r\n   the call, so we can't get the actual error directly.)\n\n\n",
                    "created": "2022-05-18T19:56:27.520+0000",
                    "updated": "2022-05-18T19:56:27.520+0000",
                    "started": "2022-05-18T19:56:27.519+0000",
                    "timeSpent": "10m",
                    "timeSpentSeconds": 600,
                    "id": "772104",
                    "issueId": "13445367"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/worklog/772105",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "comment": "github-actions[bot] commented on PR #13191:\nURL: https://github.com/apache/arrow/pull/13191#issuecomment-1130476915\n\n   https://issues.apache.org/jira/browse/ARROW-16592\n\n\n",
                    "created": "2022-05-18T19:56:47.551+0000",
                    "updated": "2022-05-18T19:56:47.551+0000",
                    "started": "2022-05-18T19:56:47.550+0000",
                    "timeSpent": "10m",
                    "timeSpentSeconds": 600,
                    "id": "772105",
                    "issueId": "13445367"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/worklog/772661",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "comment": "cyb70289 commented on code in PR #13191:\nURL: https://github.com/apache/arrow/pull/13191#discussion_r877704387\n\n\n##########\ncpp/src/arrow/flight/transport/grpc/grpc_client.cc:\n##########\n@@ -350,16 +347,7 @@ class WritableDataStream : public FinishableDataStream<Stream, ReadPayload> {\n   Status DoFinish() override {\n     // This may be used concurrently by reader/writer side of a\n     // stream, so it needs to be protected.\n-    std::lock_guard<std::mutex> guard(finish_mutex_);\n-\n-    // Now that we're shared between a reader and writer, we need to\n-    // protect ourselves from being called while there's an\n-    // outstanding read.\n-    std::unique_lock<std::mutex> read_guard(read_mutex_, std::try_to_lock);\n-    if (!read_guard.owns_lock()) {\n-      return MakeFlightError(FlightStatusCode::Internal,\n-                             \"Cannot close stream with pending read operation.\");\n-    }\n+    std::lock_guard<std::mutex> guard(read_mutex_);\n\nReview Comment:\n   Compared with original code, looks we will wait for reading finishes instead of fail immediately. Is it a problem?\r\n   \r\n   Nit: IIUC `read_mutex` is to guard concurrent `read` to `finish`. If that's the case, the name may be a bit confusing, it sounds like to guard concurrent `read` to `read`. Is `finish_mutex` a better name?\n\n\n\n",
                    "created": "2022-05-20T03:39:44.911+0000",
                    "updated": "2022-05-20T03:39:44.911+0000",
                    "started": "2022-05-20T03:39:44.911+0000",
                    "timeSpent": "10m",
                    "timeSpentSeconds": 600,
                    "id": "772661",
                    "issueId": "13445367"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/worklog/772791",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "comment": "lidavidm commented on code in PR #13191:\nURL: https://github.com/apache/arrow/pull/13191#discussion_r878059568\n\n\n##########\ncpp/src/arrow/flight/transport/grpc/grpc_client.cc:\n##########\n@@ -350,16 +347,7 @@ class WritableDataStream : public FinishableDataStream<Stream, ReadPayload> {\n   Status DoFinish() override {\n     // This may be used concurrently by reader/writer side of a\n     // stream, so it needs to be protected.\n-    std::lock_guard<std::mutex> guard(finish_mutex_);\n-\n-    // Now that we're shared between a reader and writer, we need to\n-    // protect ourselves from being called while there's an\n-    // outstanding read.\n-    std::unique_lock<std::mutex> read_guard(read_mutex_, std::try_to_lock);\n-    if (!read_guard.owns_lock()) {\n-      return MakeFlightError(FlightStatusCode::Internal,\n-                             \"Cannot close stream with pending read operation.\");\n-    }\n+    std::lock_guard<std::mutex> guard(read_mutex_);\n\nReview Comment:\n   Basically, we have three choices of behavior when gRPC returns `false` on a write (write failed, but no error info):\r\n   \r\n   1. Swallow the error and continue on until the user eventually calls Finish to get the error. (Arrow <= 7)\r\n   2. Raise a generic error to interrupt the writer, the user must catch this and still call Finish (Arrow 8)\r\n   3. Call Finish for the user and raise the actual error, _presumably_ this will complete instantly as the reason why `false` was returned means that there is already an error (this PR)\r\n   \r\n   `read_mutex` is for any read operation which includes `Finish` (this is implicitly a read)\n\n\n\n",
                    "created": "2022-05-20T11:45:33.941+0000",
                    "updated": "2022-05-20T11:45:33.941+0000",
                    "started": "2022-05-20T11:45:33.941+0000",
                    "timeSpent": "10m",
                    "timeSpentSeconds": 600,
                    "id": "772791",
                    "issueId": "13445367"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/worklog/775343",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=githubbot",
                        "name": "githubbot",
                        "key": "githubbot",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "ASF GitHub Bot",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "comment": "cyb70289 merged PR #13191:\nURL: https://github.com/apache/arrow/pull/13191\n\n\n",
                    "created": "2022-05-27T03:23:26.964+0000",
                    "updated": "2022-05-27T03:23:26.964+0000",
                    "started": "2022-05-27T03:23:26.964+0000",
                    "timeSpent": "10m",
                    "timeSpentSeconds": 600,
                    "id": "775343",
                    "issueId": "13445367"
                }
            ]
        },
        "customfield_12313920": null,
        "issuetype": {
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "id": "1",
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "name": "Bug",
            "subtask": false,
            "avatarId": 21133
        },
        "timespent": 3000,
        "customfield_12314020": "{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@45dd62f7[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@268a8f6e[overall=PullRequestOverallBean{stateCount=0, state='OPEN', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@32b6e948[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@4035f18f[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@666676df[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@6de86dee[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@681135b2[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@7c708b6[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@52c2561f[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@7c6bd6b4[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@1d36d02e[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@228be986[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\"cachedValue\":{\"errors\":[],\"configErrors\":[],\"summary\":{\"pullrequest\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":\"OPEN\",\"details\":{\"openCount\":0,\"mergedCount\":0,\"declinedCount\":0,\"total\":0},\"open\":true},\"byInstanceType\":{}},\"build\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"failedBuildCount\":0,\"successfulBuildCount\":0,\"unknownBuildCount\":0},\"byInstanceType\":{}},\"review\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":null,\"dueDate\":null,\"overDue\":false,\"completed\":false},\"byInstanceType\":{}},\"deployment-environment\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"topEnvironments\":[],\"showProjects\":false,\"successfulCount\":0},\"byInstanceType\":{}},\"repository\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}},\"branch\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}}}},\"isStale\":false}}",
        "customfield_12314141": null,
        "customfield_12314140": null,
        "project": {
            "self": "https://issues.apache.org/jira/rest/api/2/project/12319525",
            "id": "12319525",
            "key": "ARROW",
            "name": "Apache Arrow",
            "projectTypeKey": "software",
            "avatarUrls": {
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12319525&avatarId=10011",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12319525&avatarId=10011",
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12319525&avatarId=10011",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12319525&avatarId=10011"
            },
            "projectCategory": {
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/13960",
                "id": "13960",
                "description": "Apache Arrow",
                "name": "Arrow"
            }
        },
        "aggregatetimespent": 3000,
        "customfield_12312520": null,
        "customfield_12312521": "Fri May 27 03:23:39 UTC 2022",
        "customfield_12314422": null,
        "customfield_12314421": null,
        "customfield_12314146": null,
        "customfield_12314420": null,
        "customfield_12314145": null,
        "customfield_12314144": null,
        "customfield_12314143": null,
        "resolutiondate": "2022-05-27T03:23:39.000+0000",
        "workratio": -1,
        "customfield_12312923": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "watches": {
            "self": "https://issues.apache.org/jira/rest/api/2/issue/ARROW-16592/watchers",
            "watchCount": 3,
            "isWatching": false
        },
        "created": "2022-05-17T08:58:11.000+0000",
        "updated": "2022-05-27T03:23:39.000+0000",
        "timeoriginalestimate": null,
        "description": "In PyArrow 8.0.0, any error raised while handling DoPut on the server results in FlightInternalError on the client.\r\n\r\nIn PyArrow 7.0.0, errors raised while handling DoPut are propagated/converted to non-internal errors.\r\n\r\n\u2014\r\n\r\nExample: on 7.0.0, raising FlightCancelledError while handling DoPut on the server would propagate that error including extra_info all the way to the FlightClient. This is not the case anymore on 8.0.0.\r\n\r\nThe FlightInternalError contains extra detail that is derived from the cancelled error though:\r\n{code:java}\r\n/arrow/cpp/src/arrow/flight/client.cc:363: Close() failed: IOError: <error message from FlightError is here>. Detail: Cancelled. gRPC client debug context: {\"created\":\"@1652777650.446052211\",\"description\":\"Error received from peer ipv4:127.0.0.1:16001\",\"file\":\"/opt/vcpkg/buildtrees/grpc/src/85a295989c-6cf7bf442d.clean/src/core/lib/surface/call.cc\",\"file_line\":903,\"grpc_message\":\"<error message from FlightError is here>. Detail: Cancelled\",\"grpc_status\":1}. Client context: OK. Detail: Cancelled\r\n {code}\r\nNote: skimming through the code, it seems this problem is not unique to PyArrow.",
        "customfield_10010": null,
        "timetracking": {
            "remainingEstimate": "0h",
            "timeSpent": "50m",
            "remainingEstimateSeconds": 0,
            "timeSpentSeconds": 3000
        },
        "customfield_12314523": null,
        "customfield_12314127": null,
        "customfield_12314522": null,
        "customfield_12314126": null,
        "customfield_12314521": null,
        "customfield_12314125": null,
        "customfield_12314520": null,
        "customfield_12314124": null,
        "attachment": [],
        "customfield_12312340": null,
        "customfield_12314123": null,
        "customfield_12312341": null,
        "customfield_12312220": null,
        "customfield_12314122": null,
        "customfield_12314121": null,
        "customfield_12314120": null,
        "customfield_12314129": null,
        "customfield_12314524": null,
        "customfield_12314128": null,
        "summary": "[FlightRPC][Python] Regression in DoPut error handling",
        "customfield_12314130": null,
        "customfield_12310291": null,
        "customfield_12310290": null,
        "customfield_12314138": null,
        "customfield_12314137": null,
        "environment": null,
        "customfield_12314136": null,
        "customfield_12314135": null,
        "customfield_12311020": null,
        "customfield_12314134": null,
        "duedate": null,
        "customfield_12314132": null,
        "customfield_12314131": null,
        "comment": {
            "comments": [
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17538239",
                    "id": "17538239",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "body": "Can you provide a reproduction? This still works:\r\n\r\n{code:python}\r\nimport traceback\r\nimport pyarrow as pa\r\nimport pyarrow.flight as flight\r\n\r\nclass Server(flight.FlightServerBase):\r\n    def do_put(self, context, descriptor, reader, writer):\r\n        raise flight.FlightCancelledError(\"foo\", extra_info=b\"bar\")\r\n\r\n\r\nprint(\"PyArrow version:\", pa.__version__)\r\nserver = Server(\"grpc://localhost:0\")\r\nclient = flight.connect(f\"grpc://localhost:{server.port}\")\r\n\r\nschema = pa.schema([(\"a\", pa.int64())])\r\nwriter, reader = client.do_put(flight.FlightDescriptor.for_command(b\"\"), schema)\r\ntry:\r\n    writer.write_batch(pa.record_batch([[1]], schema=schema))\r\n    writer.close()\r\nexcept flight.FlightError as e:\r\n    traceback.print_exc()\r\n    print(e.extra_info)\r\nexcept Exception:\r\n    traceback.print_exc()\r\n{code}\r\n\r\n{noformat}\r\nPyArrow version: 8.0.0\r\nTraceback (most recent call last):\r\n  File \"/home/lidavidm/Code/upstream/arrow-16592/test.py\", line 18, in <module>\r\n    writer.close()\r\n  File \"pyarrow/_flight.pyx\", line 1031, in pyarrow._flight.MetadataRecordBatchWriter.close\r\n  File \"pyarrow/_flight.pyx\", line 64, in pyarrow._flight.check_flight_status\r\npyarrow._flight.FlightCancelledError: foo. Detail: Cancelled. gRPC client debug context: {\"created\":\"@1652798292.507666326\",\"description\":\"Error received from peer ipv4:127.0.0.1:42099\",\"file\":\"/home/conda/feedstock_root/build_artifacts/grpc-cpp_1651922392722/work/src/core/lib/surface/call.cc\",\"file_line\":1074,\"grpc_message\":\"foo. Detail: Cancelled\",\"grpc_status\":1}. Client context: OK\r\nb'bar'\r\n{noformat}",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "created": "2022-05-17T14:38:20.561+0000",
                    "updated": "2022-05-17T14:38:20.561+0000"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17538267",
                    "id": "17538267",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "body": "Ok, hmm, I can see this happen with the log message if I tweak things and run this enough. But that's not an exception handled in Python code, that's a warning letting you know that  you should call {{writer.close()}} or use the writer as a context manager.",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "created": "2022-05-17T15:06:32.101+0000",
                    "updated": "2022-05-17T15:06:32.101+0000"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17538370",
                    "id": "17538370",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
                        "name": "lupko",
                        "key": "JIRAUSER286791",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "Lubo Slivka",
                        "active": true,
                        "timeZone": "Europe/Prague"
                    },
                    "body": "[~lidavidm] thanks for looking into it. Let me investigate on my end - the my server has some extra 'hoops' and additional threads involved in handling the call. perhaps that is the diff. will keep you posted.",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
                        "name": "lupko",
                        "key": "JIRAUSER286791",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "Lubo Slivka",
                        "active": true,
                        "timeZone": "Europe/Prague"
                    },
                    "created": "2022-05-17T18:02:07.545+0000",
                    "updated": "2022-05-17T18:02:07.545+0000"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17538437",
                    "id": "17538437",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
                        "name": "lupko",
                        "key": "JIRAUSER286791",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "Lubo Slivka",
                        "active": true,
                        "timeZone": "Europe/Prague"
                    },
                    "body": "Hi [~lidavidm] , this was fun, I was trying many things left and right to extend the barebone reproducer with extra embellishments of my impl. No luck.\r\n\r\nSo then I tried sending same data that I'm using for my tests to your code above, and hit the internal error. Trying to narrow it down for your testcase, I got the following reproducer (the only diff from your code is the loop to write the batches):\r\n{code:java}\r\nimport traceback\r\nimport pyarrow as pa\r\nimport pyarrow.flight as flight\r\n\r\n\r\nclass Server(flight.FlightServerBase):\r\n    def do_put(self, context, descriptor, reader, writer):\r\n        raise flight.FlightCancelledError(\"foo\", extra_info=b\"bar\")\r\n\r\n\r\nprint(\"PyArrow version:\", pa.__version__)\r\nserver = Server(\"grpc://localhost:0\")\r\nclient = flight.connect(f\"grpc://localhost:{server.port}\")\r\n\r\nschema = pa.schema([(\"a\", pa.int64())])\r\nwriter, reader = client.do_put(flight.FlightDescriptor.for_command(b\"\"), schema)\r\n\r\ntry:\r\n    # starts failing at this exact number; before that the error is still cancelled\r\n    for i in range(27061):\r\n        # print(f\"write {i}\")\r\n        writer.write_batch(pa.record_batch([[1]], schema=schema))\r\n\r\n    writer.close()\r\nexcept flight.FlightError as e:\r\n    traceback.print_exc()\r\n    print(e.extra_info)\r\nexcept Exception:\r\n    traceback.print_exc() {code}\r\nnote: this may be related to timing or something, if the repro does not work, try bumping the numbers :)\u00a0\r\n\r\nwhat strikes me (and smells like the actual root cause) is that the loop goes on and does not fail after the first write. that looks awkward - could this be the real problem?\r\n\r\nalso note, I originally reproduced this with the test data that I read from CSV into a Table, and then tried doing a single writer.write_table() followed by writer.close().\r\n\r\nif needed, I can provide the test data, it's a sheet generated from tpch model.",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lupko",
                        "name": "lupko",
                        "key": "JIRAUSER286791",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "Lubo Slivka",
                        "active": true,
                        "timeZone": "Europe/Prague"
                    },
                    "created": "2022-05-17T19:59:59.729+0000",
                    "updated": "2022-05-17T20:03:51.503+0000"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17538443",
                    "id": "17538443",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "body": "Aha. Thank you so much!\r\n\r\nThat reproduces it for me. So what happens is that when writing data, gRPC crucially does not tell you if there was an error or not. It just returns boolean success/failure. (This is because there may be queueing behind the scenes, as far as I understand.) That's also why you can write data \"after\" the failure. \r\n\r\nBefore we just swallowed the error and continued on. Then you would only get the error once you finished \"writing\" (dropping all the data on the floor). Now we don't swallow the error - that's probably inadvertent, since we refactored how things work here. But the error here is \"meaningless\" because gRPC only gives a boolean. You can observe it if you do this:\r\n\r\n{code:python}\r\ntry:\r\n    # starts failing at this exact number; before that the error is still cancelled\r\n    try:\r\n        for i in range(27061):\r\n            # print(f\"write {i}\")\r\n            writer.write_batch(pa.record_batch([[1]], schema=schema))\r\n    except flight.FlightError as e:\r\n        traceback.print_exc()\r\n        print(e.extra_info)\r\n\r\n    writer.close()\r\nexcept flight.FlightError as e:\r\n    traceback.print_exc()\r\n    print(e.extra_info)\r\n{code}\r\nThe 'real' exception is still there if you call close().\r\n\r\nSo how does Close() get the \"real\" error? gRPC will give the _reader_ side of the bidirectional stream the error. But we can't actually do this inside the writer, because gRPC will crash if two threads try to read the stream at once. Now, we do have a lock. So I think the \"right\" thing to do will be, if we get an error while writing, we need to lock the read side of the stream, drain it, and raise the real error, instead of propagating the \"fake\" error (or swallowing it, which would mean your client could do a lot of unnecessary work before getting the error).",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=lidavidm",
                        "name": "lidavidm",
                        "key": "lidavidm",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"
                        },
                        "displayName": "David Li",
                        "active": true,
                        "timeZone": "America/New_York"
                    },
                    "created": "2022-05-17T20:07:03.121+0000",
                    "updated": "2022-05-17T20:07:03.121+0000"
                },
                {
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13445367/comment/17542765",
                    "id": "17542765",
                    "author": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=yibocai",
                        "name": "yibocai",
                        "key": "yibo",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=yibo&avatarId=47542",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=yibo&avatarId=47542",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=yibo&avatarId=47542",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=yibo&avatarId=47542"
                        },
                        "displayName": "Yibo Cai",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "body": "Issue resolved by pull request 13191\n[https://github.com/apache/arrow/pull/13191]",
                    "updateAuthor": {
                        "self": "https://issues.apache.org/jira/rest/api/2/user?username=yibocai",
                        "name": "yibocai",
                        "key": "yibo",
                        "avatarUrls": {
                            "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=yibo&avatarId=47542",
                            "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=yibo&avatarId=47542",
                            "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=yibo&avatarId=47542",
                            "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=yibo&avatarId=47542"
                        },
                        "displayName": "Yibo Cai",
                        "active": true,
                        "timeZone": "Etc/UTC"
                    },
                    "created": "2022-05-27T03:23:39.764+0000",
                    "updated": "2022-05-27T03:23:39.764+0000"
                }
            ],
            "maxResults": 6,
            "total": 6,
            "startAt": 0
        },
        "customfield_12311820": "0|z12flk:",
        "customfield_12314139": null
    }
}